.\" Manpage for wle.
.\" Contact contact.scottforsberg@gmail.com.
.TH man 8 "08 Jun 2019" ".4" "wle man page"
.SH NAME
wle \- extract links from a webpage
.SH SYNOPSIS
wle [ -u URL ] [ -h ] [ -v ]
.SH DESCRIPTION
This software will find urls which are found on a webpage, and display them in list form.
.SH OPTIONS
-u	input url to extract links from

-h 	display options

-v 	enables verbose output
.SH SEE ALSO
wle --help
.SH BUGS
No known bugs.
.SH AUTHOR
Scott Forsberg (contact.scottforsberg@gmail.com)
